[package]
name = "clapval"
version = "0.1.0"
edition = "2021"
license = "MIT"

description = "A validator and automatic test suite for CLAP plugins"
readme = "README.md"
repository = "https://github.com/robbert-vdh/clapval"

[dependencies]
anyhow = "1.0.58"
# All the claps!
clap = { version = "3.2.6", features = ["derive"] }
# TODO: Switch back to the crates.rs version once the debug prints are merged
clap-sys = { git = "https://github.com/robbert-vdh/clap-sys.git", branch = "feature/debug-derives" }
crossbeam = "0.8.1"
libloading = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.3"
walkdir = "2.3"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.3"
