[package]
name = "clapval"
version = "0.1.0"
edition = "2021"
license = "MIT"

description = "A validator and automatic test suite for CLAP plugins"
readme = "README.md"
repository = "https://github.com/robbert-vdh/clapval"

[dependencies]
anyhow = "1.0.58"
# All the claps!
clap = { version = "3.2.6", features = ["derive"] }
clap-sys = "0.2"
libloading = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
